PrestadorDeServico/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Prestadores_App.Models;
using System.Diagnostics;

namespace PrestadorDeServico.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrestadorDeServico/Controllers/PrestadorsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Prestadores_App.Interfaces;
using Prestadores_App.Models;

namespace PrestadorDeServico.Controllers
{
    public class PrestadorsController : Controller
    {
        private readonly IPrestadorService _PrestadorService;

        public PrestadorsController(IPrestadorService prestadorService)
        {
            _PrestadorService = prestadorService;
        }

        // GET: Prestadors
        public async Task<IActionResult> Index()
        {
            return View(await _PrestadorService.GetAll()); 
        }

        // GET: Prestadors/Create
        public IActionResult Create()
        {
            return View();
        }

  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,PhoneNumber,City,Service")] PrestadorViewModel prestador)
        {
            if (ModelState.IsValid)
            {
                await _PrestadorService.Add(prestador);
                return RedirectToAction(nameof(Index));
            }

            return View(prestador);
        }

        // GET: Prestadors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var result = await _PrestadorService.Edit(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,PhoneNumber,City,Service")] PrestadorViewModel prestador)
        {
            if (ModelState.IsValid)
            {
                await _PrestadorService.Edit(id, prestador);
                return RedirectToAction(nameof(Index));
            }
            return View(prestador);
        }

     
    }
}

PrestadorDeServico/Controllers/ServicesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Prestadores_App.Interfaces;
using Prestadores_App.Models;

namespace PrestadorDeServico.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IServicesService _serviceServices;


        public ServicesController(IServicesService serviceServices)
        {
            _serviceServices = serviceServices;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _serviceServices.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Price,Id,DateHourRegister,DateHourChange")] ServiceViewModel service)
        {
            if (ModelState.IsValid)
            {
                await _serviceServices.Add(service);
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var result = await _serviceServices.Edit(id);
            if(result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Price,Id,DateHourRegister,DateHourChange")] ServiceViewModel service)
        {
         
            if (ModelState.IsValid)
            {
                try
                {
                     var result = await _serviceServices.Edit(id, service);
                    if(result == null)
                    {
                        return NotFound();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }
    }
}

PrestadorDeServico/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<style>
    body {
        background-color: #e0e0e0;
    }
</style>

<br>
<br>
<p class="txtdia"> Soluções para o seu dia a dia </p>


<div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="./img/tinta1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="./img/furadeira1.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="./img/ferramentas1.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<!--FIM CAROUSEL-->

<br id="linkquemsomos">
<br>
<br>
<br>

<!-- INICIO QUEM SOMOS-->
<h2 class="textocentro"> SERVIÇOS.COM </h2>
<br>

<div class="container">

    <h3 class="quemsomos">

        <p class="txtquemsomos"> Quem Somos </p>
        Serviços.com é um site que mostra os prestadores de serviço. A plataforma é composta por serviços.
        Onde o usuário busque o serviço e encontre um prestador para resolver o seu problema de forma descomplicada e
        eficaz.<br><br>
        A divulgação pode ser por meio do site ou até mesmo em redes sociais.<br>
        O cliente que solicitar, não terá custo diretamente do site. O site tem como foco a praticidade,
        por isso não pedimos muitas informações, mas ficamos sempre de olho para o conforto dos nossos
        usuários.
    </h3>

</div>
<!--FIM QUEM SOMOS-->

<br>
<br>
<br id="linkservicos">
<br>

<!-- COMEÇO TEXTO -->
<br>
<br>
<p class="txtdia"> Principais Seriviços </p>
<p id="txtfelicidade"> Trabalhos mais solicitados </p>
<!--FIM TEXTO -->
<!--COMEÇO CARDS-->
<div class="container">
    <div class="card-columns">

        <div class="card shadow" style="width: 20rem;">
            <img class="card-img-top" src="./img/eletricista.jpg" alt="Imagem de capa do card">
            <div class="card-body text-center">
                <h5 class="card-title"> ELETRICISTA</h5>
                <p class="card-text"> A sua lampada queimou? Podemos te ajudar!</p>
            </div>
        </div>

        <div class="card shadow" style="width: 20rem;">
            <img class="card-img-top" src="./img/encanador.jpg" alt="Imagem de capa do card">
            <div class="card-body text-center">
                <h5 class="card-title"> ENCANADOR </h5>
                <p class="card-text">A pia da cozinha entupiu? <br> Sem problemas!</p>
            </div>
        </div>

        <div class="card shadow" style="width: 20rem;">
            <img class="card-img-top" src="./img/pintor.jpg" alt="Imagem de capa do card">
            <div class="card-body text-center">
                <h5 class="card-title"> PINTOR </h5>
                <p class="card-text">Seu filho desenhou na parede do quarto? Não surte!</p>
            </div>
        </div>
    </div>
</div>
<!--FIM CARDS-->

<br>
<br>

<!--INICIO COMO FUNCIONA-->
<div class="container" id="linkcomofunciona">
    <div style="background-color: #232323; border-radius: 10px; box-shadow: 50px 50px 1px #F29E00;">

        <!--COMEÇO TEXTO-->
        <br>
        <p class="txtcomofunciona"> Como Funciona </p>
        <p id="txtcomofunciona2"> Bem rápido e simples </p>
        <!--FIM TEXTO-->

        <br><br>

        <div class="container">
            <table style="text-align: center;">
                <tr>
                    <th style=>
                        <img class="imgresponsive" src="./img/icones/icone_form.png" width="200px">
                        <p class="txticones">CADASTRE-SE</p>
                    </th>
                    <th style="width:62%">
                        <img class="imgresponsive" src="./img/icones/icone_lupa.png" width="200px">
                        <p class="txticones">PROCURE <br> PELO SERVIÇO REQUISITADO</p>
                    </th>
                    <th>
                        <img class="imgresponsive" src="./img/icones/icone_telefone.png" width="200px">
                        <p class="txticones">ENTRE EM CONTATO COM O PRESTADOR</p>
                    </th>
                </tr>
            </table>
        </div>
    </div>
</div>

<!--FIM COMO FUNCIONA-->
<br>
<br>
<br>
<br>

PrestadorDeServico/Views/Prestadors/Create.cshtml
@model Prestadores_Domain.Entities.Prestador
 

@{ ViewData["Title"] = "Create"; }

<hr />
<br />
<br />
<br />
<section style="background:#232323;" align="center" class="container">

    <h1> CADASTRO PRESTADOR DE SERVIÇO</h1>

    <form asp-action="Create">
        <fieldset>
            <div class="container">

                <input class-"teste" asp-for="Name" class="form-control" required />
                <label>NOME</label>

            </div>
        </fieldset>

        <fieldset>
            <div class="container">

                <input id="telefone" asp-for="PhoneNumber" class="form-control" required />
                <label>TELEFONE</label>

            </div>
        </fieldset>

        <fieldset>
            <div class="container">

                <input id="email" asp-for="Email" class="form-control" required />
                <label>E-MAIL</label>

            </div>
        </fieldset>

        <fieldset>
            <div class="container">

                <p style="color: #f7f7f7">SELECIONE A CIDADE ONDE PRESTAR SERVIÇOS</p>
                <select style="width: 185px" name="City" asp-for="City" required>
                    <option type="radio" name="cidade" id="RIBEIRÃO PRETO" value="RIBEIRAO PRETO">RIBEIRÃO PRETO</option>
                    <option type="radio" name="cidade" id="SERRANA" value="SERRANA">SERRANA</option>
                    <option type="radio" name="cidade" id="SERTÃOZINHO" value="SERTAOZINHO">SERTÃOZINHO</option>
                    <option type="radio" name="cidade" id="SÃO CARLOS" value="SAO CARLOS">SÃO CARLOS</option>
                    <option type="radio" name="cidade" id="JARDINOPOLIS" value="JARDINOPOLIS">JARDINÓPOLIS</option>
                    <option type="radio" name="cidade" id="SÃO PAULO" value="SAO PAULO">SÃO PAULO</option>
                </select>


            </div>
        </fieldset>

        <fieldset>
            <div class="container">

                <p style="color: #f7f7f7">SELECIONE O SERVIÇO QUE DESEJA PRESTAR</p>
                <select style="width: 185px" name="Service" required asp->
                    @foreach (var s in Model.ServiceProvided)
                    {
                        <option type="radio" name="servico" value="@s.Name">@s.Name</option>
                                    }

                </select>


            </div>
        </fieldset>

        <br>

        <fieldset>
            <div class="container">
                <input type="submit" value="Cadastrar prestador" class="btn btn-primary" id="submit" style="background-color: #F29E00; color:#f7f7f7;" />

            </div>
        </fieldset>
    </form>
</section>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PrestadorDeServico/Views/Prestadors/Delete.cshtml
@model Prestadores_App.Models.PrestadorViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Prestador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceProvided)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceProvided)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PrestadorDeServico/Views/Prestadors/Details.cshtml
@model Prestadores_App.Models.PrestadorViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Prestador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceProvided)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceProvided)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PrestadorDeServico/Views/Prestadors/Edit.cshtml
@model Prestadores_Domain.Entities.Prestador

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Prestador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service" class="control-label"></label>
                <input asp-for="Service" class="form-control" />
                <span asp-validation-for="Service" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PrestadorDeServico/Views/Prestadors/Index.cshtml
@model IEnumerable<Prestadores_Domain.Entities.Prestador>

@{
    ViewData["Title"] = "Index";
}
<p class="txtdia"> Profissionais para facilitar o seu dia a dia </p>
<br /><br /><br />
<div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="./img/encanador_ps.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="./img/eletricista_ps.jpg" alt="Second slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<br /><br /><br />
<table class="table">
    <h1>Prestadores para o serviço</h1>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Service)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
         
            </tr>
        }
    </tbody>
</table>
<br /><br /><br />

PrestadorDeServico/Views/Services/Create.cshtml
@model Prestadores_Domain.Entities.Service

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PrestadorDeServico/Views/Services/Delete.cshtml
@model Prestadores_Domain.Entities.Service

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateHourRegister)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateHourRegister)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateHourChange)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateHourChange)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PrestadorDeServico/Views/Services/Details.cshtml
@model Prestadores_Domain.Entities.Service

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateHourRegister)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateHourRegister)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateHourChange)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateHourChange)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PrestadorDeServico/Views/Services/Edit.cshtml
@model Prestadores_Domain.Entities.Service

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DateHourRegister" class="control-label"></label>
                <input asp-for="DateHourRegister" class="form-control" />
                <span asp-validation-for="DateHourRegister" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateHourChange" class="control-label"></label>
                <input asp-for="DateHourChange" class="form-control" />
                <span asp-validation-for="DateHourChange" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PrestadorDeServico/Views/Services/Index.cshtml
@model IEnumerable<Prestadores_Domain.Entities.Service>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
         
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateHourRegister)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateHourChange)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PrestadorDeServico/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrestadorDeServico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Estilo.css" />

</head>
<body>

    <div class="navbar1 fixed-top">

        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="#"> <img src="./img/icone.png" alt=""> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
                    aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">PrestadorDeServico</a>

                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Prestadors" asp-action="Index" style="color: #F29E00;">Encontrar prestador</a>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link" href="#linkquemsomos" style="color: white;">Quem somos</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#linkservicos" style="color: white;">Serviços básicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#linkcomofunciona" style="color: white;">Como funciona</a>
                    </li>
                    <li class="nav-item">
                        <partial name="_LoginPartial" />
                    </li>

                </ul>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="linkcadastro" asp-controller="Prestadors" asp-action="Create">Cadastrar Prestador</a>

                }



            </div>
        </nav>
    </div>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PrestadorDeServico - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>